### ISSUE TITLE
Additional information about tracker in GUI

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#594]
In GUI on the tracker page we need to add some information:

* [ ] Tracker's Hardware ID
* [ ] Tracker's Firmware Version
* [ ] Tracker's vendor if we have it

**Comment by Louka3000** [comment]
We already have the last one (manufacturer)

**Comment by ImUrX** [comment]
I have a question is [this](https://github.com/SlimeVR/SolarXR-Protocol/blob/f588c2e4adc70480d7dfe23f77621d1f2183ed47/schema/datatypes/hardware_info.fbs#L45) being used as the hardware ID? Or we just using the MAC address of the device
