### ISSUE TITLE
[GUI] Home page improvements

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#655]
Bunch of improvements for the home page of the server.

* [ ] Settings section in the sidebar should always be displayed, the title "Developer Mode" should be removed. Unless in Developer/Advanced mode, only following settings should be visible: "More Info". Other options might be added there in the future.
* [x] New section for warnings should be added between the buttons and settings section in the sidebar. It will display errors and warnings that user should address. The section is not visible if there is no content in it. Things that will be displayed there, maybe more in the future:
  * [x] SlimeVR Addon is Disabled in SteamVR https://github.com/SlimeVR/SlimeVR-Server/issues/653
  * [x] There are trackers that require reset https://github.com/SlimeVR/SlimeVR-Server/issues/623#issuecomment-1481870719
  * [x] There are trackers in the error state
  * [x] There is more than one tracker assigned to the same body part
* [ ] Extension trackers should be grouped together with the main trackers. Need to come up with a good way to accomodate both modes (normal and more info), and joycons. Assume that there might be any amount of extensions in the future. #453 
* [ ] Trackers should be sorted top to bottom of the skeleton, left to right (for example, first left thigh, then right thigh), except extensions should be grouped together.
* [x] Trackers should show warning icons if there are warnings in them, like the tracker requires reset (https://github.com/SlimeVR/SlimeVR-Server/issues/623#issuecomment-1481870719) or is in the error state

**Comment by Eirenliel** [comment]
This will be reworked with new goals.
